#geonex v.1.0
resize_to: 2048
start_with: 'resize'
end_with: 'odm_postprocess'
zip_results: True
time: True
pc-quality: 'high'
sfm-algorithm: 'Incremental'
optimize-disk-space: True
pmvs_num_cores: 16 # by default this is set to $(nproc)
texturing_skip_hole_filling: False
dtm: True      # Use this tag to build a DTM (Digital Terrain Model
dsm: True      # Use this tag to build a DSM (Digital Surface Model