smrf_backup: true
memory_allocation: 120000
max_performance: true

# não usar por enquanto, afeta qualidade do orthomosaico quando zoom in
resize_to: 2048

pc-quality: high
pc-las: True
pc-filter: True
pc-csv: True

orthopfoto-kmz: True
orthophoto-cutline: True

merge: 'all'
start_with: 'resize'
end_with: 'odm_postprocess'
zip_results: True
time: True
pc-quality: 'high'
sfm-algorithm: 'Incremental'
optimize-disk-space: True
pmvs_num_cores: 16 # by default this is set to $(nproc)
texturing_skip_hole_filling: False
dtm: True      # Use this tag to build a DTM (Digital Terrain Model
dsm: True      # Use this tag to build a DSM (Digital Surface Model
pc_las: True
verbose: True
time: True
pc_tile: True
